export const BACK_EXERCISES = [
  {
    name: "Barbell Row",
    muscle: "back",
    specification: "upper",
    requirements: ["barbell"],
    variations: [],
  },
  {
    name: "Seated Row",
    muscle: "back",
    specification: "upper",
    requirements: ["machine"],
    variations: ["neutral-grip", "pronated-grip"],
  },
  {
    name: "Meadow's Row",
    muscle: "back",
    specification: "upper",
    requirements: ["barbell"],
    variations: [],
  },
  {
    name: "Dumbbell Row (Chest-Supported)",
    muscle: "back",
    specification: "upper",
    requirements: ["dumbbell", "bench"],
    variations: [],
  },
  {
    name: "Pull Ups",
    muscle: "back",
    specification: "upper",
    requirements: ["dumbbell", "bench"],
    variations: [],
  },
  {
    name: "Lat Pulldown",
    muscle: "back",
    specification: "upper",
    requirements: ["dumbbell", "bench"],
    variations: [],
  },
  {
    name: "Dumbbell Row",
    muscle: "back",
    specification: "upper",
    requirements: ["dumbbell"],
    variations: [],
  },
  {
    name: "Barbell Row (Lat-Focused)",
    muscle: "back",
    specification: "lat",
    requirements: ["barbell"],
    variations: [],
  },
  {
    name: "Seated Row (Lat-Focused)",
    muscle: "back",
    specification: "lat",
    requirements: ["machine"],
    variations: ["neutral-grip", "pronated-grip"],
  },
  {
    name: "Dumbbell Lat Row",
    muscle: "back",
    specification: "lat",
    requirements: ["dumbbell", "bench"],
    variations: ["Chest-Supported"],
  },
  {
    name: "Lat Pulldown (One-Arm)",
    muscle: "back",
    specification: "lat",
    requirements: ["machine"],
    variations: [],
  },
];
